/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './client/activitypub-api';
export * from './client/admin-api';
export * from './client/issue-api';
export * from './client/miscellaneous-api';
export * from './client/notification-api';
export * from './client/organization-api';
export * from './client/package-api';
export * from './client/repository-api';
export * from './client/settings-api';
export * from './client/user-api';

