/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlockedUser
 */
export interface BlockedUser {
    /**
     * 
     * @type {number}
     * @memberof BlockedUser
     */
    'block_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockedUser
     */
    'created_at'?: string;
}

