/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ChangedFile store information about files affected by the pull request
 * @export
 * @interface ChangedFile
 */
export interface ChangedFile {
    /**
     * 
     * @type {number}
     * @memberof ChangedFile
     */
    'additions'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChangedFile
     */
    'changes'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChangedFile
     */
    'contents_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof ChangedFile
     */
    'deletions'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChangedFile
     */
    'filename'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangedFile
     */
    'html_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangedFile
     */
    'previous_filename'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangedFile
     */
    'raw_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangedFile
     */
    'status'?: string;
}

