/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ChangeFileOperation for creating, updating or deleting a file
 * @export
 * @interface ChangeFileOperation
 */
export interface ChangeFileOperation {
    /**
     * indicates what to do with the file
     * @type {string}
     * @memberof ChangeFileOperation
     */
    'operation': ChangeFileOperationOperationEnum;
    /**
     * path to the existing or new file
     * @type {string}
     * @memberof ChangeFileOperation
     */
    'path': string;
    /**
     * new or updated file content, must be base64 encoded
     * @type {string}
     * @memberof ChangeFileOperation
     */
    'content'?: string;
    /**
     * old path of the file to move
     * @type {string}
     * @memberof ChangeFileOperation
     */
    'from_path'?: string;
    /**
     * sha is the SHA for the file that already exists, required for update or delete
     * @type {string}
     * @memberof ChangeFileOperation
     */
    'sha'?: string;
}

export const ChangeFileOperationOperationEnum = {
    Create: 'create',
    Update: 'update',
    Delete: 'delete'
} as const;

export type ChangeFileOperationOperationEnum = typeof ChangeFileOperationOperationEnum[keyof typeof ChangeFileOperationOperationEnum];


