/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreateWikiPageOptions form for creating wiki
 * @export
 * @interface CreateWikiPageOptions
 */
export interface CreateWikiPageOptions {
    /**
     * content must be base64 encoded
     * @type {string}
     * @memberof CreateWikiPageOptions
     */
    'content_base64'?: string;
    /**
     * optional commit message summarizing the change
     * @type {string}
     * @memberof CreateWikiPageOptions
     */
    'message'?: string;
    /**
     * page title. leave empty to keep unchanged
     * @type {string}
     * @memberof CreateWikiPageOptions
     */
    'title'?: string;
}

