/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreateHookOption options when create a hook
 * @export
 * @interface CreateHookOption
 */
export interface CreateHookOption {
    /**
     * CreateHookOptionConfig has all config options in it required are \"content_type\" and \"url\" Required
     * @type {{ [key: string]: string; }}
     * @memberof CreateHookOption
     */
    'config': { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CreateHookOption
     */
    'type': CreateHookOptionTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof CreateHookOption
     */
    'active'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateHookOption
     */
    'authorization_header'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateHookOption
     */
    'branch_filter'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateHookOption
     */
    'events'?: Array<string>;
}

export const CreateHookOptionTypeEnum = {
    Forgejo: 'forgejo',
    Dingtalk: 'dingtalk',
    Discord: 'discord',
    Gitea: 'gitea',
    Gogs: 'gogs',
    Msteams: 'msteams',
    Slack: 'slack',
    Telegram: 'telegram',
    Feishu: 'feishu',
    Wechatwork: 'wechatwork',
    Packagist: 'packagist'
} as const;

export type CreateHookOptionTypeEnum = typeof CreateHookOptionTypeEnum[keyof typeof CreateHookOptionTypeEnum];


