/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreatePullReviewComment } from './create-pull-review-comment';

/**
 * CreatePullReviewOptions are options to create a pull review
 * @export
 * @interface CreatePullReviewOptions
 */
export interface CreatePullReviewOptions {
    /**
     * 
     * @type {string}
     * @memberof CreatePullReviewOptions
     */
    'body'?: string;
    /**
     * 
     * @type {Array<CreatePullReviewComment>}
     * @memberof CreatePullReviewOptions
     */
    'comments'?: Array<CreatePullReviewComment>;
    /**
     * 
     * @type {string}
     * @memberof CreatePullReviewOptions
     */
    'commit_id'?: string;
    /**
     * ReviewStateType review state type
     * @type {string}
     * @memberof CreatePullReviewOptions
     */
    'event'?: string;
}

