/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreateUserOption create user options
 * @export
 * @interface CreateUserOption
 */
export interface CreateUserOption {
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    'username': string;
    /**
     * For explicitly setting the user creation timestamp. Useful when users are migrated from other systems. When omitted, the user\'s creation timestamp will be set to \"now\".
     * @type {string}
     * @memberof CreateUserOption
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    'login_name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateUserOption
     */
    'must_change_password'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateUserOption
     */
    'restricted'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateUserOption
     */
    'send_notify'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateUserOption
     */
    'source_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    'visibility'?: string;
}

