/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreateStatusOption holds the information needed to create a new CommitStatus for a Commit
 * @export
 * @interface CreateStatusOption
 */
export interface CreateStatusOption {
    /**
     * 
     * @type {string}
     * @memberof CreateStatusOption
     */
    'context'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStatusOption
     */
    'description'?: string;
    /**
     * CommitStatusState holds the state of a CommitStatus It can be \"pending\", \"success\", \"error\", \"failure\", and \"warning\"
     * @type {string}
     * @memberof CreateStatusOption
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStatusOption
     */
    'target_url'?: string;
}

