/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePushMirrorOption
 */
export interface CreatePushMirrorOption {
    /**
     * 
     * @type {string}
     * @memberof CreatePushMirrorOption
     */
    'interval'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePushMirrorOption
     */
    'remote_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePushMirrorOption
     */
    'remote_password'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePushMirrorOption
     */
    'remote_username'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePushMirrorOption
     */
    'sync_on_commit'?: boolean;
}

