/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreatePullReviewComment represent a review comment for creation api
 * @export
 * @interface CreatePullReviewComment
 */
export interface CreatePullReviewComment {
    /**
     * 
     * @type {string}
     * @memberof CreatePullReviewComment
     */
    'body'?: string;
    /**
     * if comment to new file line or 0
     * @type {number}
     * @memberof CreatePullReviewComment
     */
    'new_position'?: number;
    /**
     * if comment to old file line or 0
     * @type {number}
     * @memberof CreatePullReviewComment
     */
    'old_position'?: number;
    /**
     * the tree path
     * @type {string}
     * @memberof CreatePullReviewComment
     */
    'path'?: string;
}

