/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Cron represents a Cron task
 * @export
 * @interface Cron
 */
export interface Cron {
    /**
     * 
     * @type {number}
     * @memberof Cron
     */
    'exec_times'?: number;
    /**
     * 
     * @type {string}
     * @memberof Cron
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cron
     */
    'next'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cron
     */
    'prev'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cron
     */
    'schedule'?: string;
}

