/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DeleteEmailOption options when deleting email addresses
 * @export
 * @interface DeleteEmailOption
 */
export interface DeleteEmailOption {
    /**
     * email addresses to delete
     * @type {Array<string>}
     * @memberof DeleteEmailOption
     */
    'emails'?: Array<string>;
}

