/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EditOrgOption options for editing an organization
 * @export
 * @interface EditOrgOption
 */
export interface EditOrgOption {
    /**
     * 
     * @type {string}
     * @memberof EditOrgOption
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditOrgOption
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditOrgOption
     */
    'location'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditOrgOption
     */
    'repo_admin_change_team_access'?: boolean;
    /**
     * possible values are `public`, `limited` or `private`
     * @type {string}
     * @memberof EditOrgOption
     */
    'visibility'?: EditOrgOptionVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof EditOrgOption
     */
    'website'?: string;
}

export const EditOrgOptionVisibilityEnum = {
    Public: 'public',
    Limited: 'limited',
    Private: 'private'
} as const;

export type EditOrgOptionVisibilityEnum = typeof EditOrgOptionVisibilityEnum[keyof typeof EditOrgOptionVisibilityEnum];


