/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EditMilestoneOption options for editing a milestone
 * @export
 * @interface EditMilestoneOption
 */
export interface EditMilestoneOption {
    /**
     * 
     * @type {string}
     * @memberof EditMilestoneOption
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditMilestoneOption
     */
    'due_on'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditMilestoneOption
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditMilestoneOption
     */
    'title'?: string;
}

