/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EditIssueOption options for editing an issue
 * @export
 * @interface EditIssueOption
 */
export interface EditIssueOption {
    /**
     * deprecated
     * @type {string}
     * @memberof EditIssueOption
     */
    'assignee'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditIssueOption
     */
    'assignees'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EditIssueOption
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditIssueOption
     */
    'due_date'?: string;
    /**
     * 
     * @type {number}
     * @memberof EditIssueOption
     */
    'milestone'?: number;
    /**
     * 
     * @type {string}
     * @memberof EditIssueOption
     */
    'ref'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditIssueOption
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditIssueOption
     */
    'title'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditIssueOption
     */
    'unset_due_date'?: boolean;
}

