/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EditReleaseOption options when editing a release
 * @export
 * @interface EditReleaseOption
 */
export interface EditReleaseOption {
    /**
     * 
     * @type {string}
     * @memberof EditReleaseOption
     */
    'body'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditReleaseOption
     */
    'draft'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EditReleaseOption
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditReleaseOption
     */
    'prerelease'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EditReleaseOption
     */
    'tag_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditReleaseOption
     */
    'target_commitish'?: string;
}

