/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EditBranchProtectionOption options for editing a branch protection
 * @export
 * @interface EditBranchProtectionOption
 */
export interface EditBranchProtectionOption {
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    'approvals_whitelist_teams'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    'approvals_whitelist_username'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'block_on_official_review_requests'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'block_on_outdated_branch'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'block_on_rejected_reviews'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'dismiss_stale_approvals'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'enable_approvals_whitelist'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'enable_merge_whitelist'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'enable_push'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'enable_push_whitelist'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'enable_status_check'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    'merge_whitelist_teams'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    'merge_whitelist_usernames'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EditBranchProtectionOption
     */
    'protected_file_patterns'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'push_whitelist_deploy_keys'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    'push_whitelist_teams'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    'push_whitelist_usernames'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof EditBranchProtectionOption
     */
    'require_signed_commits'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EditBranchProtectionOption
     */
    'required_approvals'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditBranchProtectionOption
     */
    'status_check_contexts'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EditBranchProtectionOption
     */
    'unprotected_file_patterns'?: string;
}

