/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EditIssueCommentOption options for editing a comment
 * @export
 * @interface EditIssueCommentOption
 */
export interface EditIssueCommentOption {
    /**
     * 
     * @type {string}
     * @memberof EditIssueCommentOption
     */
    'body': string;
}

