/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * FileLinksResponse contains the links for a repo\'s file
 * @export
 * @interface FileLinksResponse
 */
export interface FileLinksResponse {
    /**
     * 
     * @type {string}
     * @memberof FileLinksResponse
     */
    'git'?: string;
    /**
     * 
     * @type {string}
     * @memberof FileLinksResponse
     */
    'html'?: string;
    /**
     * 
     * @type {string}
     * @memberof FileLinksResponse
     */
    'self'?: string;
}

