/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommitMeta } from './commit-meta';
// May contain unused imports in some cases
// @ts-ignore
import { CommitUser } from './commit-user';

/**
 * 
 * @export
 * @interface FileCommitResponse
 */
export interface FileCommitResponse {
    /**
     * 
     * @type {CommitUser}
     * @memberof FileCommitResponse
     */
    'author'?: CommitUser;
    /**
     * 
     * @type {CommitUser}
     * @memberof FileCommitResponse
     */
    'committer'?: CommitUser;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    'html_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    'message'?: string;
    /**
     * 
     * @type {Array<CommitMeta>}
     * @memberof FileCommitResponse
     */
    'parents'?: Array<CommitMeta>;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    'sha'?: string;
    /**
     * 
     * @type {CommitMeta}
     * @memberof FileCommitResponse
     */
    'tree'?: CommitMeta;
    /**
     * 
     * @type {string}
     * @memberof FileCommitResponse
     */
    'url'?: string;
}

