/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ContentsResponse } from './contents-response';
// May contain unused imports in some cases
// @ts-ignore
import { FileCommitResponse } from './file-commit-response';
// May contain unused imports in some cases
// @ts-ignore
import { PayloadCommitVerification } from './payload-commit-verification';

/**
 * FilesResponse contains information about multiple files from a repo
 * @export
 * @interface FilesResponse
 */
export interface FilesResponse {
    /**
     * 
     * @type {FileCommitResponse}
     * @memberof FilesResponse
     */
    'commit'?: FileCommitResponse;
    /**
     * 
     * @type {Array<ContentsResponse>}
     * @memberof FilesResponse
     */
    'files'?: Array<ContentsResponse>;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof FilesResponse
     */
    'verification'?: PayloadCommitVerification;
}

