/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ContentsResponse } from './contents-response';
// May contain unused imports in some cases
// @ts-ignore
import { FileCommitResponse } from './file-commit-response';
// May contain unused imports in some cases
// @ts-ignore
import { PayloadCommitVerification } from './payload-commit-verification';

/**
 * FileResponse contains information about a repo\'s file
 * @export
 * @interface FileResponse
 */
export interface FileResponse {
    /**
     * 
     * @type {FileCommitResponse}
     * @memberof FileResponse
     */
    'commit'?: FileCommitResponse;
    /**
     * 
     * @type {ContentsResponse}
     * @memberof FileResponse
     */
    'content'?: ContentsResponse;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof FileResponse
     */
    'verification'?: PayloadCommitVerification;
}

