/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * GeneralAPISettings contains global api settings exposed by it
 * @export
 * @interface GeneralAPISettings
 */
export interface GeneralAPISettings {
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    'default_git_trees_per_page'?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    'default_max_blob_size'?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    'default_paging_num'?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    'max_response_items'?: number;
}

