/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IssueConfigValidation
 */
export interface IssueConfigValidation {
    /**
     * 
     * @type {string}
     * @memberof IssueConfigValidation
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IssueConfigValidation
     */
    'valid'?: boolean;
}

