/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * IssueFormField represents a form field
 * @export
 * @interface IssueFormField
 */
export interface IssueFormField {
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof IssueFormField
     */
    'attributes'?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof IssueFormField
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueFormField
     */
    'type'?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof IssueFormField
     */
    'validations'?: { [key: string]: object; };
}

