/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * IssueLabelsOption a collection of labels
 * @export
 * @interface IssueLabelsOption
 */
export interface IssueLabelsOption {
    /**
     * list of label IDs
     * @type {Array<number>}
     * @memberof IssueLabelsOption
     */
    'labels'?: Array<number>;
}

