/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Attachment } from './attachment';
// May contain unused imports in some cases
// @ts-ignore
import { Label } from './label';
// May contain unused imports in some cases
// @ts-ignore
import { Milestone } from './milestone';
// May contain unused imports in some cases
// @ts-ignore
import { PullRequestMeta } from './pull-request-meta';
// May contain unused imports in some cases
// @ts-ignore
import { RepositoryMeta } from './repository-meta';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * Issue represents an issue in a repository
 * @export
 * @interface Issue
 */
export interface Issue {
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof Issue
     */
    'assets'?: Array<Attachment>;
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    'assignee'?: User;
    /**
     * 
     * @type {Array<User>}
     * @memberof Issue
     */
    'assignees'?: Array<User>;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'closed_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    'comments'?: number;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'due_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'html_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    'id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Issue
     */
    'is_locked'?: boolean;
    /**
     * 
     * @type {Array<Label>}
     * @memberof Issue
     */
    'labels'?: Array<Label>;
    /**
     * 
     * @type {Milestone}
     * @memberof Issue
     */
    'milestone'?: Milestone;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    'number'?: number;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'original_author'?: string;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    'original_author_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    'pin_order'?: number;
    /**
     * 
     * @type {PullRequestMeta}
     * @memberof Issue
     */
    'pull_request'?: PullRequestMeta;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'ref'?: string;
    /**
     * 
     * @type {RepositoryMeta}
     * @memberof Issue
     */
    'repository'?: RepositoryMeta;
    /**
     * StateType issue state type
     * @type {string}
     * @memberof Issue
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'url'?: string;
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    'user'?: User;
}

