/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * IssueDeadline represents an issue deadline
 * @export
 * @interface IssueDeadline
 */
export interface IssueDeadline {
    /**
     * 
     * @type {string}
     * @memberof IssueDeadline
     */
    'due_date'?: string;
}

