/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * IssueMeta basic issue information
 * @export
 * @interface IssueMeta
 */
export interface IssueMeta {
    /**
     * 
     * @type {number}
     * @memberof IssueMeta
     */
    'index'?: number;
    /**
     * 
     * @type {string}
     * @memberof IssueMeta
     */
    'owner'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueMeta
     */
    'repo'?: string;
}

