/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * LabelTemplate info of a Label template
 * @export
 * @interface LabelTemplate
 */
export interface LabelTemplate {
    /**
     * 
     * @type {string}
     * @memberof LabelTemplate
     */
    'color'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabelTemplate
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LabelTemplate
     */
    'exclusive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LabelTemplate
     */
    'name'?: string;
}

