/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * LicensesListEntry is used for the API
 * @export
 * @interface LicensesTemplateListEntry
 */
export interface LicensesTemplateListEntry {
    /**
     * 
     * @type {string}
     * @memberof LicensesTemplateListEntry
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof LicensesTemplateListEntry
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof LicensesTemplateListEntry
     */
    'url'?: string;
}

