/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * MarkupOption markup options
 * @export
 * @interface MarkupOption
 */
export interface MarkupOption {
    /**
     * Context to render  in: body
     * @type {string}
     * @memberof MarkupOption
     */
    'Context'?: string;
    /**
     * File path for detecting extension in file mode  in: body
     * @type {string}
     * @memberof MarkupOption
     */
    'FilePath'?: string;
    /**
     * Mode to render (comment, gfm, markdown, file)  in: body
     * @type {string}
     * @memberof MarkupOption
     */
    'Mode'?: string;
    /**
     * Text markup to render  in: body
     * @type {string}
     * @memberof MarkupOption
     */
    'Text'?: string;
    /**
     * Is it a wiki page ?  in: body
     * @type {boolean}
     * @memberof MarkupOption
     */
    'Wiki'?: boolean;
}

