/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Milestone milestone is a collection of issues on one repository
 * @export
 * @interface Milestone
 */
export interface Milestone {
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'closed_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof Milestone
     */
    'closed_issues'?: number;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'due_on'?: string;
    /**
     * 
     * @type {number}
     * @memberof Milestone
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Milestone
     */
    'open_issues'?: number;
    /**
     * StateType issue state type
     * @type {string}
     * @memberof Milestone
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'updated_at'?: string;
}

