/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * NewIssuePinsAllowed represents an API response that says if new Issue Pins are allowed
 * @export
 * @interface NewIssuePinsAllowed
 */
export interface NewIssuePinsAllowed {
    /**
     * 
     * @type {boolean}
     * @memberof NewIssuePinsAllowed
     */
    'issues'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NewIssuePinsAllowed
     */
    'pull_requests'?: boolean;
}

