/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NodeInfoUsageUsers } from './node-info-usage-users';

/**
 * NodeInfoUsage contains usage statistics for this server
 * @export
 * @interface NodeInfoUsage
 */
export interface NodeInfoUsage {
    /**
     * 
     * @type {number}
     * @memberof NodeInfoUsage
     */
    'localComments'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeInfoUsage
     */
    'localPosts'?: number;
    /**
     * 
     * @type {NodeInfoUsageUsers}
     * @memberof NodeInfoUsage
     */
    'users'?: NodeInfoUsageUsers;
}

