/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * NodeInfoServices contains the third party sites this server can connect to via their application API
 * @export
 * @interface NodeInfoServices
 */
export interface NodeInfoServices {
    /**
     * 
     * @type {Array<string>}
     * @memberof NodeInfoServices
     */
    'inbound'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof NodeInfoServices
     */
    'outbound'?: Array<string>;
}

