/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * NodeInfoUsageUsers contains statistics about the users of this server
 * @export
 * @interface NodeInfoUsageUsers
 */
export interface NodeInfoUsageUsers {
    /**
     * 
     * @type {number}
     * @memberof NodeInfoUsageUsers
     */
    'activeHalfyear'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeInfoUsageUsers
     */
    'activeMonth'?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeInfoUsageUsers
     */
    'total'?: number;
}

