/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NodeInfoServices } from './node-info-services';
// May contain unused imports in some cases
// @ts-ignore
import { NodeInfoSoftware } from './node-info-software';
// May contain unused imports in some cases
// @ts-ignore
import { NodeInfoUsage } from './node-info-usage';

/**
 * NodeInfo contains standardized way of exposing metadata about a server running one of the distributed social networks
 * @export
 * @interface NodeInfo
 */
export interface NodeInfo {
    /**
     * 
     * @type {object}
     * @memberof NodeInfo
     */
    'metadata'?: object;
    /**
     * 
     * @type {boolean}
     * @memberof NodeInfo
     */
    'openRegistrations'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof NodeInfo
     */
    'protocols'?: Array<string>;
    /**
     * 
     * @type {NodeInfoServices}
     * @memberof NodeInfo
     */
    'services'?: NodeInfoServices;
    /**
     * 
     * @type {NodeInfoSoftware}
     * @memberof NodeInfo
     */
    'software'?: NodeInfoSoftware;
    /**
     * 
     * @type {NodeInfoUsage}
     * @memberof NodeInfo
     */
    'usage'?: NodeInfoUsage;
    /**
     * 
     * @type {string}
     * @memberof NodeInfo
     */
    'version'?: string;
}

