/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Commit } from './commit';

/**
 * Note contains information related to a git note
 * @export
 * @interface Note
 */
export interface Note {
    /**
     * 
     * @type {Commit}
     * @memberof Note
     */
    'commit'?: Commit;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    'message'?: string;
}

