/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth2Application
 */
export interface OAuth2Application {
    /**
     * 
     * @type {string}
     * @memberof OAuth2Application
     */
    'client_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuth2Application
     */
    'client_secret'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OAuth2Application
     */
    'confidential_client'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OAuth2Application
     */
    'created'?: string;
    /**
     * 
     * @type {number}
     * @memberof OAuth2Application
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof OAuth2Application
     */
    'name'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OAuth2Application
     */
    'redirect_uris'?: Array<string>;
}

