/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * OrganizationPermissions list different users permissions on an organization
 * @export
 * @interface OrganizationPermissions
 */
export interface OrganizationPermissions {
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    'can_create_repository'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    'can_read'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    'can_write'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    'is_admin'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    'is_owner'?: boolean;
}

