/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Repository } from './repository';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * Package represents a package
 * @export
 * @interface Package
 */
export interface Package {
    /**
     * 
     * @type {string}
     * @memberof Package
     */
    'created_at'?: string;
    /**
     * 
     * @type {User}
     * @memberof Package
     */
    'creator'?: User;
    /**
     * 
     * @type {number}
     * @memberof Package
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Package
     */
    'name'?: string;
    /**
     * 
     * @type {User}
     * @memberof Package
     */
    'owner'?: User;
    /**
     * 
     * @type {Repository}
     * @memberof Package
     */
    'repository'?: Repository;
    /**
     * 
     * @type {string}
     * @memberof Package
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Package
     */
    'version'?: string;
}

