/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * PayloadUser represents the author or committer of a commit
 * @export
 * @interface PayloadUser
 */
export interface PayloadUser {
    /**
     * 
     * @type {string}
     * @memberof PayloadUser
     */
    'email'?: string;
    /**
     * Full name of the commit author
     * @type {string}
     * @memberof PayloadUser
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayloadUser
     */
    'username'?: string;
}

