/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PayloadCommitVerification } from './payload-commit-verification';
// May contain unused imports in some cases
// @ts-ignore
import { PayloadUser } from './payload-user';

/**
 * PayloadCommit represents a commit
 * @export
 * @interface PayloadCommit
 */
export interface PayloadCommit {
    /**
     * 
     * @type {Array<string>}
     * @memberof PayloadCommit
     */
    'added'?: Array<string>;
    /**
     * 
     * @type {PayloadUser}
     * @memberof PayloadCommit
     */
    'author'?: PayloadUser;
    /**
     * 
     * @type {PayloadUser}
     * @memberof PayloadCommit
     */
    'committer'?: PayloadUser;
    /**
     * sha1 hash of the commit
     * @type {string}
     * @memberof PayloadCommit
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommit
     */
    'message'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PayloadCommit
     */
    'modified'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PayloadCommit
     */
    'removed'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommit
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommit
     */
    'url'?: string;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof PayloadCommit
     */
    'verification'?: PayloadCommitVerification;
}

