/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Permission represents a set of permissions
 * @export
 * @interface Permission
 */
export interface Permission {
    /**
     * 
     * @type {boolean}
     * @memberof Permission
     */
    'admin'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Permission
     */
    'pull'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Permission
     */
    'push'?: boolean;
}

