/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * PullRequestMeta PR info if an issue is a PR
 * @export
 * @interface PullRequestMeta
 */
export interface PullRequestMeta {
    /**
     * 
     * @type {boolean}
     * @memberof PullRequestMeta
     */
    'merged'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PullRequestMeta
     */
    'merged_at'?: string;
}

