/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Label } from './label';
// May contain unused imports in some cases
// @ts-ignore
import { Milestone } from './milestone';
// May contain unused imports in some cases
// @ts-ignore
import { PRBranchInfo } from './prbranch-info';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * PullRequest represents a pull request
 * @export
 * @interface PullRequest
 */
export interface PullRequest {
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    'allow_maintainer_edit'?: boolean;
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    'assignee'?: User;
    /**
     * 
     * @type {Array<User>}
     * @memberof PullRequest
     */
    'assignees'?: Array<User>;
    /**
     * 
     * @type {PRBranchInfo}
     * @memberof PullRequest
     */
    'base'?: PRBranchInfo;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'closed_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    'comments'?: number;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'diff_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'due_date'?: string;
    /**
     * 
     * @type {PRBranchInfo}
     * @memberof PullRequest
     */
    'head'?: PRBranchInfo;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'html_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    'id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    'is_locked'?: boolean;
    /**
     * 
     * @type {Array<Label>}
     * @memberof PullRequest
     */
    'labels'?: Array<Label>;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'merge_base'?: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'merge_commit_sha'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    'mergeable'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    'merged'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'merged_at'?: string;
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    'merged_by'?: User;
    /**
     * 
     * @type {Milestone}
     * @memberof PullRequest
     */
    'milestone'?: Milestone;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    'number'?: number;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'patch_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    'pin_order'?: number;
    /**
     * 
     * @type {Array<User>}
     * @memberof PullRequest
     */
    'requested_reviewers'?: Array<User>;
    /**
     * StateType issue state type
     * @type {string}
     * @memberof PullRequest
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    'url'?: string;
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    'user'?: User;
}

