/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * PushMirror represents information of a push mirror
 * @export
 * @interface PushMirror
 */
export interface PushMirror {
    /**
     * 
     * @type {string}
     * @memberof PushMirror
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof PushMirror
     */
    'interval'?: string;
    /**
     * 
     * @type {string}
     * @memberof PushMirror
     */
    'last_error'?: string;
    /**
     * 
     * @type {string}
     * @memberof PushMirror
     */
    'last_update'?: string;
    /**
     * 
     * @type {string}
     * @memberof PushMirror
     */
    'remote_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof PushMirror
     */
    'remote_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PushMirror
     */
    'repo_name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PushMirror
     */
    'sync_on_commit'?: boolean;
}

