/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * RenameUserOption options when renaming a user
 * @export
 * @interface RenameUserOption
 */
export interface RenameUserOption {
    /**
     * New username for this user. This name cannot be in use yet by any other user.
     * @type {string}
     * @memberof RenameUserOption
     */
    'new_username': string;
}

