/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * RepoTopicOptions a collection of repo topic names
 * @export
 * @interface RepoTopicOptions
 */
export interface RepoTopicOptions {
    /**
     * list of topic names
     * @type {Array<string>}
     * @memberof RepoTopicOptions
     */
    'topics'?: Array<string>;
}

