/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * RepositoryMeta basic repository information
 * @export
 * @interface RepositoryMeta
 */
export interface RepositoryMeta {
    /**
     * 
     * @type {string}
     * @memberof RepositoryMeta
     */
    'full_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof RepositoryMeta
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RepositoryMeta
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RepositoryMeta
     */
    'owner'?: string;
}

