/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommitMeta } from './commit-meta';
// May contain unused imports in some cases
// @ts-ignore
import { CommitUser } from './commit-user';
// May contain unused imports in some cases
// @ts-ignore
import { PayloadCommitVerification } from './payload-commit-verification';

/**
 * 
 * @export
 * @interface RepoCommit
 */
export interface RepoCommit {
    /**
     * 
     * @type {CommitUser}
     * @memberof RepoCommit
     */
    'author'?: CommitUser;
    /**
     * 
     * @type {CommitUser}
     * @memberof RepoCommit
     */
    'committer'?: CommitUser;
    /**
     * 
     * @type {string}
     * @memberof RepoCommit
     */
    'message'?: string;
    /**
     * 
     * @type {CommitMeta}
     * @memberof RepoCommit
     */
    'tree'?: CommitMeta;
    /**
     * 
     * @type {string}
     * @memberof RepoCommit
     */
    'url'?: string;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof RepoCommit
     */
    'verification'?: PayloadCommitVerification;
}

