/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ExternalTracker } from './external-tracker';
// May contain unused imports in some cases
// @ts-ignore
import { ExternalWiki } from './external-wiki';
// May contain unused imports in some cases
// @ts-ignore
import { InternalTracker } from './internal-tracker';
// May contain unused imports in some cases
// @ts-ignore
import { Permission } from './permission';
// May contain unused imports in some cases
// @ts-ignore
import { RepoTransfer } from './repo-transfer';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * Repository represents a repository
 * @export
 * @interface Repository
 */
export interface Repository {
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'allow_merge_commits'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'allow_rebase'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'allow_rebase_explicit'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'allow_rebase_update'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'allow_squash_merge'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'archived'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'archived_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'avatar_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'clone_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'created_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'default_allow_maintainer_edit'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'default_branch'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'default_delete_branch_after_merge'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'default_merge_style'?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'empty'?: boolean;
    /**
     * 
     * @type {ExternalTracker}
     * @memberof Repository
     */
    'external_tracker'?: ExternalTracker;
    /**
     * 
     * @type {ExternalWiki}
     * @memberof Repository
     */
    'external_wiki'?: ExternalWiki;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'fork'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    'forks_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'full_name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'has_actions'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'has_issues'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'has_packages'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'has_projects'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'has_pull_requests'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'has_releases'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'has_wiki'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'html_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    'id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'ignore_whitespace_conflicts'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'internal'?: boolean;
    /**
     * 
     * @type {InternalTracker}
     * @memberof Repository
     */
    'internal_tracker'?: InternalTracker;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'language'?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'languages_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'link'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'mirror'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'mirror_interval'?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'mirror_updated'?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    'open_issues_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    'open_pr_counter'?: number;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'original_url'?: string;
    /**
     * 
     * @type {User}
     * @memberof Repository
     */
    'owner'?: User;
    /**
     * 
     * @type {Repository}
     * @memberof Repository
     */
    'parent'?: Repository;
    /**
     * 
     * @type {Permission}
     * @memberof Repository
     */
    'permissions'?: Permission;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'private'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    'release_counter'?: number;
    /**
     * 
     * @type {RepoTransfer}
     * @memberof Repository
     */
    'repo_transfer'?: RepoTransfer;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'ssh_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    'stars_count'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    'template'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'url'?: string;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    'watchers_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    'website'?: string;
}

