/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ServerVersion wraps the version of the server
 * @export
 * @interface ServerVersion
 */
export interface ServerVersion {
    /**
     * 
     * @type {string}
     * @memberof ServerVersion
     */
    'version'?: string;
}

