/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * StopWatch represent a running stopwatch
 * @export
 * @interface StopWatch
 */
export interface StopWatch {
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    'duration'?: string;
    /**
     * 
     * @type {number}
     * @memberof StopWatch
     */
    'issue_index'?: number;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    'issue_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    'repo_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    'repo_owner_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof StopWatch
     */
    'seconds'?: number;
}

