/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommitMeta } from './commit-meta';

/**
 * Tag represents a repository tag
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * 
     * @type {CommitMeta}
     * @memberof Tag
     */
    'commit'?: CommitMeta;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    'tarball_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    'zipball_url'?: string;
}

