/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Comment } from './comment';
// May contain unused imports in some cases
// @ts-ignore
import { Issue } from './issue';
// May contain unused imports in some cases
// @ts-ignore
import { Label } from './label';
// May contain unused imports in some cases
// @ts-ignore
import { Milestone } from './milestone';
// May contain unused imports in some cases
// @ts-ignore
import { Team } from './team';
// May contain unused imports in some cases
// @ts-ignore
import { TrackedTime } from './tracked-time';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * TimelineComment represents a timeline comment (comment of any type) on a commit or issue
 * @export
 * @interface TimelineComment
 */
export interface TimelineComment {
    /**
     * 
     * @type {User}
     * @memberof TimelineComment
     */
    'assignee'?: User;
    /**
     * 
     * @type {Team}
     * @memberof TimelineComment
     */
    'assignee_team'?: Team;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'created_at'?: string;
    /**
     * 
     * @type {Issue}
     * @memberof TimelineComment
     */
    'dependent_issue'?: Issue;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'html_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimelineComment
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'issue_url'?: string;
    /**
     * 
     * @type {Label}
     * @memberof TimelineComment
     */
    'label'?: Label;
    /**
     * 
     * @type {Milestone}
     * @memberof TimelineComment
     */
    'milestone'?: Milestone;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'new_ref'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'new_title'?: string;
    /**
     * 
     * @type {Milestone}
     * @memberof TimelineComment
     */
    'old_milestone'?: Milestone;
    /**
     * 
     * @type {number}
     * @memberof TimelineComment
     */
    'old_project_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'old_ref'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'old_title'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimelineComment
     */
    'project_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'pull_request_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'ref_action'?: string;
    /**
     * 
     * @type {Comment}
     * @memberof TimelineComment
     */
    'ref_comment'?: Comment;
    /**
     * commit SHA where issue/PR was referenced
     * @type {string}
     * @memberof TimelineComment
     */
    'ref_commit_sha'?: string;
    /**
     * 
     * @type {Issue}
     * @memberof TimelineComment
     */
    'ref_issue'?: Issue;
    /**
     * whether the assignees were removed or added
     * @type {boolean}
     * @memberof TimelineComment
     */
    'removed_assignee'?: boolean;
    /**
     * 
     * @type {User}
     * @memberof TimelineComment
     */
    'resolve_doer'?: User;
    /**
     * 
     * @type {number}
     * @memberof TimelineComment
     */
    'review_id'?: number;
    /**
     * 
     * @type {TrackedTime}
     * @memberof TimelineComment
     */
    'tracked_time'?: TrackedTime;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimelineComment
     */
    'updated_at'?: string;
    /**
     * 
     * @type {User}
     * @memberof TimelineComment
     */
    'user'?: User;
}

