/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * 
 * @export
 * @interface UserSearch200Response
 */
export interface UserSearch200Response {
    /**
     * 
     * @type {Array<User>}
     * @memberof UserSearch200Response
     */
    'data'?: Array<User>;
    /**
     * 
     * @type {boolean}
     * @memberof UserSearch200Response
     */
    'ok'?: boolean;
}

