/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * UserHeatmapData represents the data needed to create a heatmap
 * @export
 * @interface UserHeatmapData
 */
export interface UserHeatmapData {
    /**
     * 
     * @type {number}
     * @memberof UserHeatmapData
     */
    'contributions'?: number;
    /**
     * TimeStamp defines a timestamp
     * @type {number}
     * @memberof UserHeatmapData
     */
    'timestamp'?: number;
}

