/* tslint:disable */
/* eslint-disable */
/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * WatchInfo represents an API watch status of one repository
 * @export
 * @interface WatchInfo
 */
export interface WatchInfo {
    /**
     * 
     * @type {string}
     * @memberof WatchInfo
     */
    'created_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WatchInfo
     */
    'ignored'?: boolean;
    /**
     * 
     * @type {object}
     * @memberof WatchInfo
     */
    'reason'?: object;
    /**
     * 
     * @type {string}
     * @memberof WatchInfo
     */
    'repository_url'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WatchInfo
     */
    'subscribed'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WatchInfo
     */
    'url'?: string;
}

